version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
   
    commands:
        # install npm
        - echo "Installing npm ..."
        - npm install
       
  build:
    commands:
        # run build script
        - echo "Building files ..."
        - npm run build
artifacts:
  files: 
    - build/*
